/*
 * generated by Xtext 2.10.0
 */
package org.xtext.editor.alda.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.editor.alda.ui.internal.AldaActivator;

public class AldaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return AldaActivator.getInstance().getInjector("org.xtext.editor.alda.Alda");
	}

}
