/*
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAldaScopeProvider extends DelegatingScopeProvider {
}
