/*
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.editor.alda.AldaRuntimeModule
import org.xtext.editor.alda.AldaStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AldaIdeSetup extends AldaStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AldaRuntimeModule, new AldaIdeModule))
	}
	
}
