/*
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.editor.alda.ui.internal.AldaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AldaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AldaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AldaActivator.getInstance().getInjector(AldaActivator.ORG_XTEXT_EDITOR_ALDA_ALDA);
	}
	
}
