/*
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.editor.alda.parser.antlr.internal.InternalAldaParser;
import org.xtext.editor.alda.services.AldaGrammarAccess;

public class AldaParser extends AbstractAntlrParser {

	@Inject
	private AldaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAldaParser createParser(XtextTokenStream stream) {
		return new InternalAldaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public AldaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AldaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
