/**
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda;

import org.xtext.editor.alda.AbstractAldaRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AldaRuntimeModule extends AbstractAldaRuntimeModule {
}
