/**
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda;

import org.xtext.editor.alda.AldaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class AldaStandaloneSetup extends AldaStandaloneSetupGenerated {
  public static void doSetup() {
    AldaStandaloneSetup _aldaStandaloneSetup = new AldaStandaloneSetup();
    _aldaStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
