/*
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AldaRuntimeModule extends AbstractAldaRuntimeModule {
}
