/*
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AldaStandaloneSetup extends AldaStandaloneSetupGenerated {

	def static void doSetup() {
		new AldaStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
