grammar org.xtext.alda.Alda with org.eclipse.xtext.common.Terminals

generate alda "http://www.xtext.org/alda/Alda"

Model:
	tempo+=Tempo*
	quant+=Quant*
	volume+=Volume*
	keySignature+=KeySignature*;
	 
Tempo:
	'(''tempo' '!'? name=INT ')'
	;
	
Quant:
	'(''quant' '!'? name=INT ')'
	;
	
Volume:
	'(''volume' '!'? name=INT ')'
	;

KeySignature:
	'(''key-signature' '!'? name=NOTES ')'
	
;

terminal NOTES:
	('a'|'b'|'c'|'d'|'e'|'f'|'g')(' '('a'|'b'|'c'|'d'|'e'|'f'|'g'))*
;
