/**
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.tests;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.editor.alda.alda.Model;
import org.xtext.editor.alda.tests.AldaInjectorProvider;

/* @RunWith(/* name is null */)
@InjectWith(AldaInjectorProvider.class) */@SuppressWarnings("all")
public class AldaParsingTest {
  /* @Inject
   */private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field AldaParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
