/**
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AldaIdeModule /* implements AbstractAldaIdeModule  */{
}
