/**
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.ide;

import com.google.inject.Injector;
import org.xtext.editor.alda.AldaStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AldaIdeSetup extends AldaStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from AldaIdeModule to Module");
  }
}
