/**
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.ide;

import org.xtext.editor.alda.ide.AbstractAldaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class AldaIdeModule extends AbstractAldaIdeModule {
}
