/**
 * generated by Xtext 2.10.0
 */
package org.xtext.editor.alda.alda;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.editor.alda.alda.AldaFactory
 * @model kind="package"
 * @generated
 */
public interface AldaPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "alda";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/editor/alda/Alda";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "alda";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AldaPackage eINSTANCE = org.xtext.editor.alda.alda.impl.AldaPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.editor.alda.alda.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.editor.alda.alda.impl.ModelImpl
   * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DECLARATIONS = 0;

  /**
   * The feature id for the '<em><b>Instruments</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__INSTRUMENTS = 1;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.editor.alda.alda.impl.DECLRATIONSImpl <em>DECLRATIONS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.editor.alda.alda.impl.DECLRATIONSImpl
   * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getDECLRATIONS()
   * @generated
   */
  int DECLRATIONS = 1;

  /**
   * The number of structural features of the '<em>DECLRATIONS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLRATIONS_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.editor.alda.alda.impl.COMMENTImpl <em>COMMENT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.editor.alda.alda.impl.COMMENTImpl
   * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getCOMMENT()
   * @generated
   */
  int COMMENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMENT__NAME = DECLRATIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>COMMENT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMENT_FEATURE_COUNT = DECLRATIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.editor.alda.alda.impl.INSTRUMENTSImpl <em>INSTRUMENTS</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.editor.alda.alda.impl.INSTRUMENTSImpl
   * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getINSTRUMENTS()
   * @generated
   */
  int INSTRUMENTS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUMENTS__NAME = 0;

  /**
   * The number of structural features of the '<em>INSTRUMENTS</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.editor.alda.alda.impl.TempoImpl <em>Tempo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.editor.alda.alda.impl.TempoImpl
   * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getTempo()
   * @generated
   */
  int TEMPO = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPO__NAME = DECLRATIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tempo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPO_FEATURE_COUNT = DECLRATIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.editor.alda.alda.impl.QuantImpl <em>Quant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.editor.alda.alda.impl.QuantImpl
   * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getQuant()
   * @generated
   */
  int QUANT = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUANT__NAME = DECLRATIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Quant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUANT_FEATURE_COUNT = DECLRATIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.editor.alda.alda.impl.VolumeImpl <em>Volume</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.editor.alda.alda.impl.VolumeImpl
   * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getVolume()
   * @generated
   */
  int VOLUME = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOLUME__NAME = DECLRATIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Volume</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VOLUME_FEATURE_COUNT = DECLRATIONS_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.editor.alda.alda.impl.KeySignatureImpl <em>Key Signature</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.editor.alda.alda.impl.KeySignatureImpl
   * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getKeySignature()
   * @generated
   */
  int KEY_SIGNATURE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY_SIGNATURE__NAME = DECLRATIONS_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Key Signature</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY_SIGNATURE_FEATURE_COUNT = DECLRATIONS_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.editor.alda.alda.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.editor.alda.alda.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.editor.alda.alda.Model#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see org.xtext.editor.alda.alda.Model#getDeclarations()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Declarations();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.editor.alda.alda.Model#getInstruments <em>Instruments</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instruments</em>'.
   * @see org.xtext.editor.alda.alda.Model#getInstruments()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Instruments();

  /**
   * Returns the meta object for class '{@link org.xtext.editor.alda.alda.DECLRATIONS <em>DECLRATIONS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>DECLRATIONS</em>'.
   * @see org.xtext.editor.alda.alda.DECLRATIONS
   * @generated
   */
  EClass getDECLRATIONS();

  /**
   * Returns the meta object for class '{@link org.xtext.editor.alda.alda.COMMENT <em>COMMENT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>COMMENT</em>'.
   * @see org.xtext.editor.alda.alda.COMMENT
   * @generated
   */
  EClass getCOMMENT();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.editor.alda.alda.COMMENT#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.editor.alda.alda.COMMENT#getName()
   * @see #getCOMMENT()
   * @generated
   */
  EAttribute getCOMMENT_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.editor.alda.alda.INSTRUMENTS <em>INSTRUMENTS</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>INSTRUMENTS</em>'.
   * @see org.xtext.editor.alda.alda.INSTRUMENTS
   * @generated
   */
  EClass getINSTRUMENTS();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.editor.alda.alda.INSTRUMENTS#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.editor.alda.alda.INSTRUMENTS#getName()
   * @see #getINSTRUMENTS()
   * @generated
   */
  EAttribute getINSTRUMENTS_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.editor.alda.alda.Tempo <em>Tempo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tempo</em>'.
   * @see org.xtext.editor.alda.alda.Tempo
   * @generated
   */
  EClass getTempo();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.editor.alda.alda.Tempo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.editor.alda.alda.Tempo#getName()
   * @see #getTempo()
   * @generated
   */
  EAttribute getTempo_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.editor.alda.alda.Quant <em>Quant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Quant</em>'.
   * @see org.xtext.editor.alda.alda.Quant
   * @generated
   */
  EClass getQuant();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.editor.alda.alda.Quant#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.editor.alda.alda.Quant#getName()
   * @see #getQuant()
   * @generated
   */
  EAttribute getQuant_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.editor.alda.alda.Volume <em>Volume</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Volume</em>'.
   * @see org.xtext.editor.alda.alda.Volume
   * @generated
   */
  EClass getVolume();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.editor.alda.alda.Volume#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.editor.alda.alda.Volume#getName()
   * @see #getVolume()
   * @generated
   */
  EAttribute getVolume_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.editor.alda.alda.KeySignature <em>Key Signature</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Key Signature</em>'.
   * @see org.xtext.editor.alda.alda.KeySignature
   * @generated
   */
  EClass getKeySignature();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.editor.alda.alda.KeySignature#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.editor.alda.alda.KeySignature#getName()
   * @see #getKeySignature()
   * @generated
   */
  EAttribute getKeySignature_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AldaFactory getAldaFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.editor.alda.alda.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.editor.alda.alda.impl.ModelImpl
     * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DECLARATIONS = eINSTANCE.getModel_Declarations();

    /**
     * The meta object literal for the '<em><b>Instruments</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__INSTRUMENTS = eINSTANCE.getModel_Instruments();

    /**
     * The meta object literal for the '{@link org.xtext.editor.alda.alda.impl.DECLRATIONSImpl <em>DECLRATIONS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.editor.alda.alda.impl.DECLRATIONSImpl
     * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getDECLRATIONS()
     * @generated
     */
    EClass DECLRATIONS = eINSTANCE.getDECLRATIONS();

    /**
     * The meta object literal for the '{@link org.xtext.editor.alda.alda.impl.COMMENTImpl <em>COMMENT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.editor.alda.alda.impl.COMMENTImpl
     * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getCOMMENT()
     * @generated
     */
    EClass COMMENT = eINSTANCE.getCOMMENT();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMENT__NAME = eINSTANCE.getCOMMENT_Name();

    /**
     * The meta object literal for the '{@link org.xtext.editor.alda.alda.impl.INSTRUMENTSImpl <em>INSTRUMENTS</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.editor.alda.alda.impl.INSTRUMENTSImpl
     * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getINSTRUMENTS()
     * @generated
     */
    EClass INSTRUMENTS = eINSTANCE.getINSTRUMENTS();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTRUMENTS__NAME = eINSTANCE.getINSTRUMENTS_Name();

    /**
     * The meta object literal for the '{@link org.xtext.editor.alda.alda.impl.TempoImpl <em>Tempo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.editor.alda.alda.impl.TempoImpl
     * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getTempo()
     * @generated
     */
    EClass TEMPO = eINSTANCE.getTempo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMPO__NAME = eINSTANCE.getTempo_Name();

    /**
     * The meta object literal for the '{@link org.xtext.editor.alda.alda.impl.QuantImpl <em>Quant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.editor.alda.alda.impl.QuantImpl
     * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getQuant()
     * @generated
     */
    EClass QUANT = eINSTANCE.getQuant();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUANT__NAME = eINSTANCE.getQuant_Name();

    /**
     * The meta object literal for the '{@link org.xtext.editor.alda.alda.impl.VolumeImpl <em>Volume</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.editor.alda.alda.impl.VolumeImpl
     * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getVolume()
     * @generated
     */
    EClass VOLUME = eINSTANCE.getVolume();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VOLUME__NAME = eINSTANCE.getVolume_Name();

    /**
     * The meta object literal for the '{@link org.xtext.editor.alda.alda.impl.KeySignatureImpl <em>Key Signature</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.editor.alda.alda.impl.KeySignatureImpl
     * @see org.xtext.editor.alda.alda.impl.AldaPackageImpl#getKeySignature()
     * @generated
     */
    EClass KEY_SIGNATURE = eINSTANCE.getKeySignature();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute KEY_SIGNATURE__NAME = eINSTANCE.getKeySignature_Name();

  }

} //AldaPackage
