/**
 * generated by Xtext 2.10.0
 */
package org.xtext.editor.alda.alda;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.editor.alda.alda.AldaPackage
 * @generated
 */
public interface AldaFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AldaFactory eINSTANCE = org.xtext.editor.alda.alda.impl.AldaFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>DECLRATIONS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>DECLRATIONS</em>'.
   * @generated
   */
  DECLRATIONS createDECLRATIONS();

  /**
   * Returns a new object of class '<em>COMMENT</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>COMMENT</em>'.
   * @generated
   */
  COMMENT createCOMMENT();

  /**
   * Returns a new object of class '<em>INSTRUMENTS</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>INSTRUMENTS</em>'.
   * @generated
   */
  INSTRUMENTS createINSTRUMENTS();

  /**
   * Returns a new object of class '<em>Tempo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tempo</em>'.
   * @generated
   */
  Tempo createTempo();

  /**
   * Returns a new object of class '<em>Quant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Quant</em>'.
   * @generated
   */
  Quant createQuant();

  /**
   * Returns a new object of class '<em>Volume</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Volume</em>'.
   * @generated
   */
  Volume createVolume();

  /**
   * Returns a new object of class '<em>Key Signature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Key Signature</em>'.
   * @generated
   */
  KeySignature createKeySignature();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AldaPackage getAldaPackage();

} //AldaFactory
