/**
 * generated by Xtext 2.10.0
 */
package org.xtext.editor.alda.alda;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>DECLRATIONS</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.editor.alda.alda.AldaPackage#getDECLRATIONS()
 * @model
 * @generated
 */
public interface DECLRATIONS extends EObject
{
} // DECLRATIONS
