/**
 * generated by Xtext 2.10.0
 */
package org.xtext.editor.alda.alda;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.editor.alda.alda.Model#getDeclarations <em>Declarations</em>}</li>
 *   <li>{@link org.xtext.editor.alda.alda.Model#getInstruments <em>Instruments</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.editor.alda.alda.AldaPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Declarations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.editor.alda.alda.DECLRATIONS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declarations</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarations</em>' containment reference list.
   * @see org.xtext.editor.alda.alda.AldaPackage#getModel_Declarations()
   * @model containment="true"
   * @generated
   */
  EList<DECLRATIONS> getDeclarations();

  /**
   * Returns the value of the '<em><b>Instruments</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.editor.alda.alda.INSTRUMENTS}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Instruments</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instruments</em>' containment reference list.
   * @see org.xtext.editor.alda.alda.AldaPackage#getModel_Instruments()
   * @model containment="true"
   * @generated
   */
  EList<INSTRUMENTS> getInstruments();

} // Model
