/**
 * generated by Xtext 2.10.0
 */
package org.xtext.editor.alda.alda;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Volume</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.editor.alda.alda.Volume#getName <em>Name</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.editor.alda.alda.AldaPackage#getVolume()
 * @model
 * @generated
 */
public interface Volume extends DECLRATIONS
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(int)
   * @see org.xtext.editor.alda.alda.AldaPackage#getVolume_Name()
   * @model
   * @generated
   */
  int getName();

  /**
   * Sets the value of the '{@link org.xtext.editor.alda.alda.Volume#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(int value);

} // Volume
