/**
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.editor.alda.ui.AbstractAldaUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AldaUiModule extends AbstractAldaUiModule {
  public AldaUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
