/**
 * generated by Xtext 2.10.0
 */
package org.xtext.editor.alda.alda.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.editor.alda.alda.AldaPackage;
import org.xtext.editor.alda.alda.DECLRATIONS;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>DECLRATIONS</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class DECLRATIONSImpl extends MinimalEObjectImpl.Container implements DECLRATIONS
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DECLRATIONSImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AldaPackage.Literals.DECLRATIONS;
  }

} //DECLRATIONSImpl
