/**
 * generated by Xtext 2.12.0
 */
package org.xtext.editor.alda.ui.contentassist;

import org.xtext.editor.alda.ui.contentassist.AbstractAldaProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AldaProposalProvider extends AbstractAldaProposalProvider {
}
